// Scans generated Avro C# files and avsc schemas, then emits:
//   1. A JsonSerializerContext with [JsonSerializable] for every ISpecificRecord type
//   2. A GivenwellEventsMetadata class with a UserDataEventTypes set
// Usage: dotnet run generate-json-context.cs <srcFolder> <packageName> <avroFolder>

using System.Text.Json;
using System.Text.Json.Nodes;

var srcFolder = args[0];
var packageName = args[1];
var avroFolder = args[2];
var contextClass = packageName.Replace(".", "_") + "JsonContext";
var outputFile = Path.Combine(srcFolder, packageName, $"{packageName}JsonContext.cs");

// Collect ISpecificRecord types from generated cs files
var types = new List<(string Namespace, string ClassName)>();

foreach (var file in Directory.EnumerateFiles(Path.Combine(srcFolder, packageName), "*.cs", SearchOption.AllDirectories))
{
    var lines = File.ReadAllLines(file);

    string? ns = null;
    string? className = null;

    foreach (var line in lines)
    {
        var trimmed = line.TrimStart();
        if (ns == null && trimmed.StartsWith("namespace "))
            ns = trimmed["namespace ".Length..].Trim().TrimEnd('{').Trim();

        if (trimmed.Contains("ISpecificRecord") && trimmed.Contains("public partial class "))
        {
            var idx = trimmed.IndexOf("public partial class ") + "public partial class ".Length;
            className = trimmed[idx..].Split(' ', ':')[0].Trim();
            break;
        }
    }

    if (ns != null && className != null)
        types.Add((ns, className));
}

// Collect user data types from avsc files
var userDataTypeNames = new HashSet<string>();

foreach (var avscFile in Directory.EnumerateFiles(avroFolder, "*.avsc", SearchOption.AllDirectories))
{
    var json = File.ReadAllText(avscFile);
    var node = JsonNode.Parse(json);

    var records = node is JsonArray arr
        ? arr.OfType<JsonObject>()
        : node is JsonObject obj ? [obj] : [];

    foreach (var record in records)
    {
        if (record["type"]?.GetValue<string>() != "record") continue;

        var fields = record["fields"]?.AsArray();
        if (fields == null) continue;

        var hasUserData = fields.OfType<JsonObject>().Any(f =>
        {
            var ud = f["userData"];
            return ud != null && (ud.GetValue<bool?>() == true || ud.GetValue<string?>() == "true");
        });

        if (hasUserData)
        {
            var name = record["name"]?.GetValue<string>();
            if (name != null) userDataTypeNames.Add(name);
        }
    }
}

var userDataTypes = types.Where(t => userDataTypeNames.Contains(t.ClassName)).ToList();

// Write context file
var jsonSerializableAttrs = string.Join("\n", types.Select(t => $"[JsonSerializable(typeof({t.Namespace}.{t.ClassName}))]"));
var userDataTypesList = string.Join(",\n        ", userDataTypes.Select(t => $"typeof({t.Namespace}.{t.ClassName})"));

var content = $$"""
    // <auto-generated/>
    using System.Text.Json.Serialization;

    {{jsonSerializableAttrs}}
    public partial class {{contextClass}} : JsonSerializerContext;

    public static class GivenwellEventsMetadata
    {
        public static readonly IReadOnlySet<System.Type> UserDataEventTypes = new System.Collections.Generic.HashSet<System.Type>
        {
            {{userDataTypesList}}
        };
    }
    """;

File.WriteAllText(outputFile, content);
Console.WriteLine($"Generated {outputFile} with {types.Count} types, {userDataTypes.Count} user data types.");
