// Scans generated Avro C# files and emits a JsonSerializerContext
// Usage: dotnet run generate-json-context.cs <srcFolder> <packageName>

var srcFolder = args[0];
var packageName = args[1];
var contextClass = packageName.Replace(".", "_") + "JsonContext";
var outputFile = Path.Combine(srcFolder, packageName, $"{packageName}JsonContext.cs");

var attributes = new List<string>();

foreach (var file in Directory.EnumerateFiles(Path.Combine(srcFolder, packageName), "*.cs", SearchOption.AllDirectories))
{
    var lines = File.ReadAllLines(file);

    string? ns = null;
    string? className = null;

    foreach (var line in lines)
    {
        var trimmed = line.TrimStart();
        if (ns == null && trimmed.StartsWith("namespace "))
            ns = trimmed["namespace ".Length..].Trim().TrimEnd('{').Trim();

        if (trimmed.Contains("ISpecificRecord") && trimmed.Contains("public partial class "))
        {
            var idx = trimmed.IndexOf("public partial class ") + "public partial class ".Length;
            className = trimmed[idx..].Split(' ', ':')[0].Trim();
            break;
        }
    }

    if (ns != null && className != null)
        attributes.Add($"[JsonSerializable(typeof({ns}.{className}))]");
}

var content = $$"""
    // <auto-generated/>
    using System.Text.Json.Serialization;

    {{string.Join("\n", attributes)}}
    public partial class {{contextClass}} : JsonSerializerContext;
    """;

File.WriteAllText(outputFile, content);
Console.WriteLine($"Generated {outputFile} with {attributes.Count} types.");
